#!/bin/bash

dotfiles=(
  ".gitconfig"
  ".ideavimrc"
  ".tmux.conf"
  ".vimrc"
  ".zshrc"
)

config_dirs=(
  "alacritty"
  "atuin"
  "bat"
  "btop"
  "fastfetch"
  "fish"
  "fontconfig"
  "helix"
  "kitty"
  "lsd"
  "mpv"
  "neofetch"
  "nvim"
  "sheldon"
  "starship.toml"
  "yazi"
)

for file in "${dotfiles[@]}"; do
  rm -rf $HOME/$file
  ln -s "$HOME/git/dotfiles/$file" "$HOME/$file"
done

for dir in "${config_dirs[@]}"; do
  rm -rf $HOME/.config/$dir
  ln -s "$HOME/git/dotfiles/.config/$dir" "$HOME/.config/$dir"
done
