# I just don't want that in my .zshrc
# It's so ugly
alias alipan='aliyunpan-go'
alias ap='~/code/shell/ap.sh'
alias c='clear'
alias cC='sudo rm -rf ~/.cache/* && echo "Done!"'
alias cn='LANG=zh_CN.UTF-8 LANGUAGE=zh_CN.UTF-8'
alias du='du -h'
alias e='emacs -nw'
alias f='fastfetch'
alias gh='cd ~ && clear'
alias hx='helix'
alias kcp='kdeconnect-cli -n V2048A --share'
alias lg='lazygit'
alias ls='lsd'
alias lst='lsd --tree'
alias mm='micromamba'
alias n='neofetch'
alias nv='nvim'
alias nvh='nvim ~/.histfile'
alias sc='systemctl'
alias sg='sgpt'
alias sgi='sgpt --repl tmp'
alias sgs='sgpt --repl shell --shell'
alias sgc='rm -rf /tmp/shell_gpt && echo "Done!"'
alias sl='lsd'
alias sz='source ~/.zshrc'
alias sn='sudo nvim'
alias ts='sudo timeshift --create --tags D'
alias tsd='sudo timeshift --delete'
alias tt='tgpt'
alias tti='tgpt -i'
alias ttm='tgpt -m'
alias tts='tgpt -s'
alias ttc='tgpt -c'
