# I just don't want that in my .zshrc
# It's so ugly
alias ap="~/create_ap.sh"
alias apu="sudo ifconfig ap0 up"
alias apd="sudo ifconfig ap0 down"
alias b1="echo 750 | sudo tee /sys/class/backlight/intel_backlight/brightness"
alias b2="echo 1500 | sudo tee /sys/class/backlight/intel_backlight/brightness"
alias b3="echo 2250 | sudo tee /sys/class/backlight/intel_backlight/brightness"
alias b4="echo 3000 | sudo tee /sys/class/backlight/intel_backlight/brightness"
alias b5="echo 3750 | sudo tee /sys/class/backlight/intel_backlight/brightness"
alias b6="echo 4500 | sudo tee /sys/class/backlight/intel_backlight/brightness"
alias b7="echo 5250 | sudo tee /sys/class/backlight/intel_backlight/brightness"
alias b8="echo 6000 | sudo tee /sys/class/backlight/intel_backlight/brightness"
alias b9="echo 6750 | sudo tee /sys/class/backlight/intel_backlight/brightness"
alias b0="echo 7500 | sudo tee /sys/class/backlight/intel_backlight/brightness"
alias c="clear"
alias ca="conda activate"
alias cC="sudo rm -rf ~/.cache/*"
alias ct="cd ~/tmp"
alias cip="curl cip.cc"
alias cy="curl -vv www.youtube.com"
alias cg="cargo"
alias du="du -h"
alias gh="cd ~ && clear"
alias glog="git log --pretty=oneline --all --graph --abbrev-commit"
alias gd="git diff"
alias hs="hexo clean && hexo g && hexo s"
alias hn="hexo new"
alias hd="hexo d"
alias ig="ifconfig"
alias kcp="kdeconnect-cli -n V2048A --share"
alias kcw="kdeconnect-cli -n WayDroid x86_64 --share"
alias ls="ls --color=auto"
alias lg="lazygit"
alias ll="ls -ahl --color=auto"
alias n="neofetch"
alias nv="nvim"
alias nvz="nvim ~/.zshrc"
alias pyv="python --version"
alias sc="systemctl"
alias sl="ls"
alias sg="sgpt"
alias sgi="sgpt --repl tmp"
alias sgs="sgpt --repl shell --shell"
alias sgc="sudo rm -rf /tmp/shell_gpt"
alias sz="source ~/.zshrc"
alias sn="sudo nvim"
alias t="tmux"
alias ts="sudo timeshift --create --tags D"
alias tsd="sudo timeshift --delete"
alias u="yay"
alias up="cd .."
alias vu="systemctl start v2raya"
alias vd="systemctl stop v2raya"
alias venv="source ./venv/bin/activate"
alias vm="sc start vmware-usbarbitrator vmware-networks"
alias yc="yay -Scc"
