# I just don't want that in my .zshrc
# It's so ugly
alias aq='asciiquarium'
alias c='clear'
alias ca='conda activate'
alias cC='sudo rm -rf ~/.cache/* && echo "Done!"'
alias du='du -h'
alias gh='cd ~ && clear'
alias hx='helix'
alias kcp='kdeconnect-cli -n V2048A --share'
alias lg='lazygit'
alias ls='lsd'
alias lst='lsd --tree'
alias n='neofetch'
alias nv='nvim'
alias nvh='nvim ~/.histfile'
alias sc='systemctl'
alias sl='lsd'
alias sg='sgpt'
alias sga='sgpt --role assistant'
alias sgi='sgpt --repl tmp'
alias sgs='sgpt --repl shell --shell'
alias sgc='rm -rf /tmp/shell_gpt && echo "Done!"'
alias sz='source ~/.zshrc'
alias sn='sudo nvim'
alias ts='sudo timeshift --create --tags D'
alias tsd='sudo timeshift --delete'
